" 设置显示文件行数
set number

" 设置主题默认的风格为Dark
set background=dark

" 使用我们settings/*下的配置文件
source ~/.vim/settings/plugins.vim
source ~/.vim/settings/configs.vim

" 默认会使用当前目录下的配置
if filereadable(".vimrc")
  source .vimrc
  " echom "Loaded custom .vimrc within " . getcwd()
endif